const express = require('express')
const cors = require('cors')
const cookieParser = require('cookie-parser')
require('dotenv').config({ path:'./.env'})
const connectToDatabase = require('./database/connectToDatabase')
const productRoutes = require('./routes/productRoutes')
const userRoutes = require('./routes/userRoutes')
const orderRoutes = require('./routes/orderRoutes')
const PORT = process.env.PORT || 4000
const app = express()
connectToDatabase()
app.use(cors())
app.use(express.json())
app.use(cookieParser())
app.use('/api/v1', productRoutes)
app.use('/api/v1',userRoutes)
app.use('/api/v1',orderRoutes)
app.listen(PORT, () => {
    console.log(`server is running on http://localhost:${PORT}`);
})