const express = require('express')
const authJwtToken = require("../middleware/authJwtToken")
const authenticateRoles = require("../middleware/authAccessRoles")
const { createProduct, updateProduct, getProducts, fetchProductDetails, deleteProduct, createAndUpdateReview, getReviews, deleteReview, deleteWonReview } = require('../controller/productController')
const router = express.Router()
router.route('/admin/product/new').post(authJwtToken,authenticateRoles("admin"),createProduct)
router.route('/admin/product/:id?').put(authJwtToken,authenticateRoles("admin"),updateProduct).delete(authJwtToken,authenticateRoles("admin"),deleteProduct)
router.route('/product/:id?').get(fetchProductDetails)
router.route('/products').get(getProducts)
router.route('/user/review').put(authJwtToken, authenticateRoles("admin", "user"), createAndUpdateReview)
router.route('/reviews').get(getReviews)
router.route('/user/review/remove').delete(authJwtToken,authenticateRoles("admin", "user"), deleteWonReview)
router.route('/admin/review/remove').delete(authJwtToken,authenticateRoles("admin"), deleteReview)
module.exports = router